package com.signavio.droolsexport._2e0512d53e2b42f28a3ea8e98225ff9f._1 

import java.time.OffsetTime
import java.util.Arrays
import com.signavio.dmn.formulae.DmnHierarchyFormulae
import java.text.DecimalFormat
import com.signavio.dmn.formulae.DmnFormulae
import java.util.ArrayList
import java.util.HashSet
import java.math.BigDecimal
import java.util.List
import java.time.OffsetDateTime
import java.time.LocalDate
import java.util.Collections
import java.math.RoundingMode

global String modelId
global Integer revisionNumber

declare  DmnFormulae 
end

declare  DmnFormulaeLocal  extends  DmnFormulae  
end

declare  DmnHierarchyFormulae 
end

declare  Input 
    in : Boolean  
end

declare  Decision_Output 
    decision : BigDecimal  
end

rule "initialize_version_info"
    salience 1000
when
then
	drools.getWorkingMemory().setGlobal("modelId", "2e0512d53e2b42f28a3ea8e98225ff9f");
	drools.getWorkingMemory().setGlobal("revisionNumber", 1);
end

rule "add_formulae_to_memory"
    salience 1000
when
then
	insert(new DmnFormulaeLocal());
	insert(new DmnHierarchyFormulae());
end

rule "decision_rule_1"
    no-loop 
    salience 1
when
    $F : DmnFormulaeLocal(  )  
    $H : DmnHierarchyFormulae(  )  
    not( 
    Decision_Output(  )   ) 
    $input : Input(  )  
    eval( $F.nullSafeEval($F.equals($input.getIn(), true)) ) 
then
	Decision_Output $decision_Output = new Decision_Output();
	$decision_Output.setDecision(BigDecimal.valueOf(1.0));
	insert($decision_Output);
end

rule "decision_rule_2"
    no-loop 
    salience 1
when
    $F : DmnFormulaeLocal(  )  
    $H : DmnHierarchyFormulae(  )  
    not( 
    Decision_Output(  )   ) 
    $input : Input(  )  
    eval( $F.nullSafeEval($F.equals($input.getIn(), false)) ) 
then
	Decision_Output $decision_Output = new Decision_Output();
	$decision_Output.setDecision(BigDecimal.valueOf(0.0));
	insert($decision_Output);
end

rule "decision_emptyResultFallBack"
    no-loop 
    //decision:  decision
    salience -1
when
    $F : DmnFormulaeLocal(  )  
    $H : DmnHierarchyFormulae(  )  
    not( 
    Decision_Output(  )   ) 
    $input : Input(  )  
then
	Decision_Output $decision_Output = new Decision_Output();
	$decision_Output.setDecision(null);
	insert($decision_Output);
end
